height: 1080
regions:
  overlay: { height: 0.7, width: 0.15, x: 0.85, y: 0.2 }
  result: { height: 0.04, width: 0.15, x: 0.42, y: 0.13 }
  start: { height: 0.1, width: 0.2, x: 0.4, y: 0.3 }
templates: {}
width: 1920
